# config/packages/nelmio_cors.yaml
nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: ['http://localhost:3000']  # URL de votre frontend React
        allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With']
        allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'OPTIONS']
        expose_headers: ['Link']
        max_age: 3600
        hosts: []
        origin_regex: false
        forced_allow_origin_value: ~
    paths:
        '^/api/':
            allow_origin: ['http://localhost:3000']  # URL de votre frontend React
            allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'OPTIONS']
            max_age: 3600
        '^/':
            origin_regex: true
            allow_origin: ['^http://localhost:[0-9]+']
            allow_headers: ['Content-Type', 'Authorization']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'OPTIONS']
            max_age: 3600
