# config/packages/nelmio_cors.yaml
nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: ['*']  # Autoriser toutes les origines en développement
        allow_headers: ['*']  # Autoriser tous les headers
        allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'OPTIONS']
        expose_headers: ['*']
        max_age: 3600
        hosts: []
        origin_regex: true
        forced_allow_origin_value: ~
    paths:
        '^/api/':
            allow_origin: ['*']
            allow_headers: ['*']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'OPTIONS']
            max_age: 3600
        '^/':
            origin_regex: true
            allow_origin: ['*']
            allow_headers: ['*']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'OPTIONS']
            max_age: 3600
