version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/MayRent/front"
    schedule:
      interval: "weekly"
  - package-ecosystem: "composer"
    directory: "/MayRent/back"
    schedule:
      interval: "weekly" 