version: '3.8'

services:
  # Backend service
  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    volumes:
      - ./back:/var/www
    depends_on:
      - db
    networks:
      - app-network

  # Frontend service
  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile.dev
    volumes:
      - ./front:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    depends_on:
      - backend
    networks:
      - app-network

  # Nginx service
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./back:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - backend
    networks:
      - app-network

  # Database service
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: mayrent
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata: 