<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSaOjKzU\App_KernelProdDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSaOjKzU/App_KernelProdDebugContainer.php') {
    touch(__DIR__.'/ContainerSaOjKzU.legacy');

    return;
}

if (!\class_exists(App_KernelProdDebugContainer::class, false)) {
    \class_alias(\ContainerSaOjKzU\App_KernelProdDebugContainer::class, App_KernelProdDebugContainer::class, false);
}

return new \ContainerSaOjKzU\App_KernelProdDebugContainer([
    'container.build_hash' => 'SaOjKzU',
    'container.build_id' => 'ae750d6f',
    'container.build_time' => 1750946842,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSaOjKzU');
