<?php

namespace Container5x3NbGC;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInscriptionControllerregisterService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.LenB0IS.App\Controller\InscriptionController::register()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.LenB0IS.App\\Controller\\InscriptionController::register()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'passwordHasher' => ['privates', 'security.user_password_hasher', 'getSecurity_UserPasswordHasherService', true],
            'validator' => ['privates', 'debug.validator', 'getDebug_ValidatorService', false],
            'jwtManager' => ['services', 'lexik_jwt_authentication.jwt_manager', 'getLexikJwtAuthentication_JwtManagerService', true],
        ], [
            'entityManager' => '?',
            'passwordHasher' => '?',
            'validator' => '?',
            'jwtManager' => '?',
        ]))->withContext('App\\Controller\\InscriptionController::register()', $container);
    }
}
