<?php

namespace ContainerA9vSdsm;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReservationControllergetReservationsForVoitureService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.f9M7wQ5.App\Controller\ReservationController::getReservationsForVoiture()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.f9M7wQ5.App\\Controller\\ReservationController::getReservationsForVoiture()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'locationRepository' => ['privates', 'App\\Repository\\LocationRepository', 'getLocationRepositoryService', true],
        ], [
            'locationRepository' => 'App\\Repository\\LocationRepository',
        ]))->withContext('App\\Controller\\ReservationController::getReservationsForVoiture()', $container);
    }
}
