<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Voiture extends \App\Entity\Voiture implements \Doctrine\ORM\Proxy\InternalProxy
{
     use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'couleur' => [parent::class, 'couleur', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'id_categorie' => [parent::class, 'id_categorie', null],
        "\0".parent::class."\0".'id_client' => [parent::class, 'id_client', null],
        "\0".parent::class."\0".'immatriculation' => [parent::class, 'immatriculation', null],
        "\0".parent::class."\0".'modele' => [parent::class, 'modele', null],
        "\0".parent::class."\0".'prix_jour' => [parent::class, 'prix_jour', null],
        "\0".parent::class."\0".'puissance' => [parent::class, 'puissance', null],
        'couleur' => [parent::class, 'couleur', null],
        'id' => [parent::class, 'id', null],
        'id_categorie' => [parent::class, 'id_categorie', null],
        'id_client' => [parent::class, 'id_client', null],
        'immatriculation' => [parent::class, 'immatriculation', null],
        'modele' => [parent::class, 'modele', null],
        'prix_jour' => [parent::class, 'prix_jour', null],
        'puissance' => [parent::class, 'puissance', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
