version: '3'

services:
  back:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "9000"
    volumes:
      - ./public:/var/www/public

  nginx:
    build:
      context: ../nginx
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ../back/public:/var/www/public
      - ../nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - back

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: myrent
      MYSQL_USER: noa
      MYSQL_PASSWORD: nono6969
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: {}
