<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerA9vSdsm\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerA9vSdsm/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerA9vSdsm.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerA9vSdsm\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerA9vSdsm\App_KernelTestDebugContainer([
    'container.build_hash' => 'A9vSdsm',
    'container.build_id' => 'cff109e5',
    'container.build_time' => 1751296409,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerA9vSdsm');
