<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLLyIhqr\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLLyIhqr/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLLyIhqr.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLLyIhqr\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLLyIhqr\App_KernelDevDebugContainer([
    'container.build_hash' => 'LLyIhqr',
    'container.build_id' => '7b6557b6',
    'container.build_time' => 1750972923,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLLyIhqr');
