<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBd2bm6y\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBd2bm6y/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBd2bm6y.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBd2bm6y\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBd2bm6y\App_KernelDevDebugContainer([
    'container.build_hash' => 'Bd2bm6y',
    'container.build_id' => '3c53d401',
    'container.build_time' => 1750919009,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBd2bm6y');
