<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXtKAnSH\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXtKAnSH/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXtKAnSH.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXtKAnSH\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXtKAnSH\App_KernelDevDebugContainer([
    'container.build_hash' => 'XtKAnSH',
    'container.build_id' => 'ee1e9bad',
    'container.build_time' => 1745936049,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXtKAnSH');
