<?php

namespace ContainerCSPqw4N;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVoitureCrudControllerconfigureCrudService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.GLGWHcU.App\Controller\Admin\VoitureCrudController::configureCrud()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.GLGWHcU.App\\Controller\\Admin\\VoitureCrudController::configureCrud()'] = ($container->privates['.service_locator.GLGWHcU'] ?? $container->load('get_ServiceLocator_GLGWHcUService'))->withContext('App\\Controller\\Admin\\VoitureCrudController::configureCrud()', $container);
    }
}
